version: "3.3"
services:

  mongo:
    image: mongo:3.4
    networks:
      - mongo
    deploy:
      replicas: 3
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
      endpoint_mode: dnsrr
    command: 'mongod --replSet "rs0"'

  mongo-setup:
    image: wacccourse/mongo-setup:latest
    networks:
      - mongo
    environment:
      SERVICE_NAME: mongo
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure

networks:
  mongo:
    driver: overlay
    internal: true
