version: "3.3"
services:

  frontend:
    image: wacc-frontend
    build: ./frontend
    networks:
      - gateway
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"

networks:
  gateway:
    driver: overlay
